### ISSUE TITLE
the setup is using an api from 7.1

### ISSUE THREAD

**Issue by kalsky** [QualiSystems/cloudshell-orch-sandbox#19]
We need to have a separate branch that maintains to 7.0 released scripts and push bug fixes to it if needed or have the code written in a way that supports backward compatibility.
Currently the latest code here has api calls that are available only in 7.1 (PrepareSandboxConnectivity for example).

**Comment by alexazarh** [comment]
Created a release branch for 7.0:
https://github.com/QualiSystems/cloudshell-orch-sandbox/tree/release/v7.0
